# Configuración de entrenamiento y arquitectura del modelo

batch_size: 64
epochs: 30
learning_rate: 0.001
test_size: 0.2
random_state: 42

model:
  hidden_layers: [64, 32]
  activation: tanh
  output_activation: sigmoid