# Configuración de entrenamiento y arquitectura del modelo

batch_size: 32
epochs: 100
learning_rate: 0.0005
test_size: 0.2
random_state: 42

model:
  hidden_layers: [256, 128, 64, 32]
  activation: relu
  output_activation: sigmoid