# Configuraci칩n de rutas y par치metros

paths:
  raw_data: "/Users/sebazamorano/Downloads/subconjunto_items_comprimido"             # Ruta original descargada
  prepared_data: "/Users/sebazamorano/Downloads/subconjunto_items_comprimido"          # Donde se copiar치n las im치genes organizadas por clase
  model: "models/cnn_multiclass.keras"

image:
  height: 64
  width: 64
  channels: 3

training:
  batch_size: 32
  epochs: 20
  patience: 5
  dropout: 0.5
  optimizer: "adam"

evaluation:
  threshold: 0.5