paths:
  # Carpeta raíz con los 3 splits
  raw_data: "Projects/Supermarket/data"
  prepared_data: "Projects/Supermarket/data"

  # Splits explícitos
  train_dir: "Projects/Supermarket/data/train"
  val_dir:   "Projects/Supermarket/data/val"
  test_dir:  "Projects/Supermarket/data/test"

  # Dónde guardaremos el modelo entrenado
  model: "Projects/Supermarket/models/cnn_multiclass.pt"
